development:
  adapter: postgresql
  encoding: utf8
  database: db/project_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: db/project_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: db/project_production
  pool: 5